app = "brandrdxmusic-x46dna"
primary_region = "cdg"
kill_timeout = 300

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python3 -m BrandrdXMusic"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[swap]]
  size_mb = 512
